import type { BrandConfig } from "@mvp/ui";

export const brand: BrandConfig = {
  id: "lv-laboratorio",
  nome: "LV",
  nomeDestaque: "LABORATÓRIO DENTAL",
  tagline: "De Prótese Dentária",
  cidade: "Caxias do Sul",
  estado: "RS",
  responsavelLabel: "Responsável técnico",
  responsavelNome: "Lucas de Vargas",
  headline: "Cada detalhe importa quando o sorriso é de verdade.",
  subheadline: "Atendimento próximo durante todo o desenvolvimento do seu caso, do planejamento ao acabamento.",
  statusFlow: [
    "Caso recebido",
    "Em análise",
    "Planejamento",
    "Em produção",
    "Acabamento",
    "Aguardando aprovação",
    "Pronto para entrega",
    "Finalizado",
  ],
  dashboard: {
    statCards: [
      {
        label: "Trabalhos ativos",
        tipo: "status",
        statuses: [
          "Caso recebido",
          "Em análise",
          "Planejamento",
          "Em produção",
          "Acabamento",
          "Aguardando aprovação",
          "Pronto para entrega",
        ],
      },
      { label: "Em produção", tipo: "status", statuses: ["Em produção", "Acabamento"] },
      { label: "Aguardando aprovação", tipo: "status", statuses: ["Aguardando aprovação"] },
      { label: "Prontos para entrega", tipo: "status", statuses: ["Pronto para entrega"] },
      { label: "Atrasados", tipo: "atrasadas" },
    ],
  },
  textos: {
    loginTitulo: "Organização para cada etapa do seu trabalho.",
    loginSubtitulo: "Mais precisão, controle e proximidade em cada caso.",
    loginBotaoPrincipal: "Entrar no sistema",
    loginLinkSecundario: "Acessar demonstração",
    dashboardTituloLab: "Visão geral dos seus trabalhos.",
    dashboardSubtituloLab: "Cada caso, acompanhado de perto.",
    dashboardTituloClinica: "Seus trabalhos em andamento.",
    dashboardSubtituloClinica: "Acompanhe cada etapa, do planejamento à entrega.",
    novaOrdemTitulo: "Comece um novo trabalho.",
    novaOrdemSubtitulo: "Envie os dados do caso e organize as informações antes da produção.",
    uploadTitulo: "Envie o escaneamento e os arquivos do caso.",
    uploadSubtitulo: "STL, imagens e documentos organizados em um único lugar.",
  },
  cores: {
    primaria: "#00A8E0",
    primariaEscura: "#0089B8",
    fundo: "#F7FAFC",
    superficie: "#FFFFFF",
    texto: "#102F4A",
    textoSecundario: "#637789",
    borda: "#DCE7EF",
    sidebarFundo: "#063B70",
    sidebarTexto: "#D7E6F2",
    sidebarAccent: "#0A4A85",
    sidebarAccentTexto: "#FFFFFF",
    sidebarBorda: "#0F5590",
    sidebarPrimaria: "#00A8E0",
    statusNeutroBg: "#EEF3F7",
    statusNeutroTexto: "#637789",
    statusInfoBg: "#E5F6FC",
    statusInfoTexto: "#00789E",
    statusAlertaBg: "#FDF4E3",
    statusAlertaTexto: "#8A5C14",
    statusSucessoBg: "#E8F5F0",
    statusSucessoTexto: "#2E9B78",
    statusErroBg: "#FBEAEA",
    statusErroTexto: "#B23B3B",
  },
  fontes: {
    titulo: "'Manrope', sans-serif",
    corpo: "'Inter', sans-serif",
    mono: "'Manrope', sans-serif",
  },
  logoPath: "/brand/logo.webp",
};
