import type { BrandConfig } from "@mvp/ui";

export const brand: BrandConfig = {
  id: "dlab-digital",
  nome: "DLAB",
  nomeDestaque: "DIGITAL",
  tagline: "Fluxo Digital",
  cidade: "Curitiba",
  estado: "PR",
  responsavelLabel: "Fundador",
  responsavelNome: "Dr. Geninho Thomé",
  headline: "Fluxo digital completo. Precisão em cada etapa.",
  subheadline: "Do planejamento à entrega — cada caso, uma sequência precisa.",
  statusFlow: ["Recebido", "Em produção", "Em prova", "Finalizado"],
  statusAprovacao: "Em prova",
  dashboard: {
    statCards: [
      { label: "Recebidos", tipo: "status", statuses: ["Recebido"] },
      { label: "Em produção", tipo: "status", statuses: ["Em produção"] },
      { label: "Em prova", tipo: "status", statuses: ["Em prova"] },
      { label: "Finalizados", tipo: "status", statuses: ["Finalizado"] },
      { label: "Atrasados", tipo: "atrasadas" },
    ],
  },
  textos: {
    loginTitulo: "Entrar",
    loginSubtitulo: "Acesso restrito à equipe DLAB Digital e clínicas parceiras.",
    loginBotaoPrincipal: "Entrar",
    loginLinkSecundario: "Acessar como clínica (demonstração)",
    dashboardTituloLab: "Visão geral do fluxo digital",
    dashboardSubtituloLab: "Controle cada trabalho do planejamento à entrega.",
    dashboardTituloClinica: "Mais integração entre clínica e laboratório",
    dashboardSubtituloClinica: "Acompanhe seus casos em tempo real, do planejamento à entrega.",
    novaOrdemTitulo: "Novo trabalho",
    novaOrdemSubtitulo: "Cada caso, uma sequência precisa.",
    uploadTitulo: "Envie os arquivos do caso",
    uploadSubtitulo: "STL, PLY, OBJ ou imagens — organizados do planejamento à entrega.",
  },
  cores: {
    primaria: "#D7D7D7",
    primariaEscura: "#B8B8B8",
    primariaTexto: "#0B0B0B",
    inputBg: "#0B0B0B",
    fundo: "#151515",
    superficie: "#202020",
    texto: "#F5F5F5",
    textoSecundario: "#A6A6A6",
    borda: "#343434",
    sidebarFundo: "#0B0B0B",
    sidebarTexto: "#A6A6A6",
    sidebarAccent: "#202020",
    sidebarAccentTexto: "#F5F5F5",
    sidebarBorda: "#343434",
    sidebarPrimaria: "#D7D7D7",
    statusNeutroBg: "#1C1C1C",
    statusNeutroTexto: "#A6A6A6",
    statusInfoBg: "#232323",
    statusInfoTexto: "#C7C7C7",
    statusAlertaBg: "#2A2210",
    statusAlertaTexto: "#D9A441",
    statusSucessoBg: "#12241C",
    statusSucessoTexto: "#42B883",
    statusErroBg: "#2A1717",
    statusErroTexto: "#C95B5B",
  },
  fontes: {
    titulo: "'Space Grotesk', sans-serif",
    corpo: "'Inter', sans-serif",
    mono: "'Space Grotesk', sans-serif",
  },
  logoPath: "/brand/logo.png",
  sidebarLogoSomenteImagem: true,
};
