import type { BrandConfig } from "@mvp/ui";

export const brand: BrandConfig = {
  id: "dlab-digital",
  nome: "DLAB",
  nomeDestaque: "DIGITAL",
  tagline: "Fluxo Digital",
  cidade: "Curitiba",
  estado: "PR",
  responsavelLabel: "Fundador",
  responsavelNome: "Dr. Geninho Thomé",
  headline: "Fluxo digital de ponta a ponta, da moldagem à prótese finalizada.",
  subheadline:
    "Acompanhe barras sobre implante, guias cirúrgicos e próteses digitais com rastreabilidade técnica em cada etapa da produção.",
  statusFlow: ["Recebida", "Em análise", "Em produção", "Em prova", "Pronta", "Enviada/Entregue"],
  dashboard: {
    statCards: [
      { label: "Novas", tipo: "status", statuses: ["Recebida"] },
      { label: "Em produção", tipo: "status", statuses: ["Em análise", "Em produção", "Em prova"] },
      { label: "Prontas", tipo: "status", statuses: ["Pronta"] },
      { label: "Atrasadas", tipo: "atrasadas" },
    ],
  },
  textos: {
    loginTitulo: "Entrar",
    loginSubtitulo: "Acesso das clínicas e dentistas parceiros. Use o e-mail e a senha do seu cadastro.",
    loginBotaoPrincipal: "Entrar",
    loginLinkSecundario: "Acessar como clínica (demonstração)",
    dashboardTituloLab: "Painel do laboratório",
    dashboardSubtituloLab: "Todas as ordens das clínicas parceiras da DLAB DIGITAL",
    dashboardTituloClinica: "Minhas ordens",
    dashboardSubtituloClinica: "Ordens enviadas pela sua clínica",
    novaOrdemTitulo: "Nova ordem de serviço",
    novaOrdemSubtitulo: "Preencha os dados do caso. O número da ordem é gerado automaticamente.",
    uploadTitulo: "Arraste arquivos aqui ou clique para selecionar",
    uploadSubtitulo: "Envie o planejamento digital, tomografias e documentos do caso.",
  },
  cores: {
    primaria: "#1E293B",
    primariaEscura: "#0F172A",
    fundo: "#F4F5F7",
    superficie: "#FFFFFF",
    texto: "#111827",
    textoSecundario: "#4B5563",
    borda: "#E1E4E9",
    sidebarFundo: "#0A0E14",
    sidebarTexto: "#D7DBE2",
    sidebarAccent: "#181F2B",
    sidebarAccentTexto: "#FFFFFF",
    sidebarBorda: "#232A38",
    sidebarPrimaria: "#7C8CF8",
    statusNeutroBg: "#F1F5F9",
    statusNeutroTexto: "#334155",
    statusInfoBg: "#EFF6FF",
    statusInfoTexto: "#1D4ED8",
    statusAlertaBg: "#FFFBEB",
    statusAlertaTexto: "#92400E",
    statusSucessoBg: "#ECFDF5",
    statusSucessoTexto: "#047857",
    statusErroBg: "#FEF2F2",
    statusErroTexto: "#B91C1C",
  },
  fontes: {
    titulo: "'Space Grotesk', sans-serif",
    corpo: "'IBM Plex Sans', sans-serif",
    mono: "'IBM Plex Mono', monospace",
  },
  logoPath: "/brand/logo.png",
};
