import type { BrandConfig } from "@mvp/ui";

export const brand: BrandConfig = {
  id: "ultra-dental",
  nome: "ULTRA",
  nomeDestaque: "DENTAL LAB",
  tagline: "Precisão Digital",
  cidade: "Maringá",
  estado: "PR",
  responsavelLabel: "Técnico responsável",
  responsavelNome: "Equipe Ultra Dental Lab",
  headline: "Precisão CAD/CAM do escaneamento à fresagem em cinco eixos.",
  subheadline:
    "Rastreie cada caso em tempo real, envie arquivos STL e PLY e fale direto com o técnico responsável pelo seu trabalho.",
  statusFlow: ["Recebida", "Em análise", "Em produção", "Em prova", "Pronta", "Enviada/Entregue"],
  dashboard: {
    statCards: [
      { label: "Novas", tipo: "status", statuses: ["Recebida"] },
      { label: "Em produção", tipo: "status", statuses: ["Em análise", "Em produção", "Em prova"] },
      { label: "Prontas", tipo: "status", statuses: ["Pronta"] },
      { label: "Atrasadas", tipo: "atrasadas" },
    ],
  },
  textos: {
    loginTitulo: "Entrar",
    loginSubtitulo: "Acesso das clínicas e dentistas parceiros. Use o e-mail e a senha do seu cadastro.",
    loginBotaoPrincipal: "Entrar",
    loginLinkSecundario: "Acessar como clínica (demonstração)",
    dashboardTituloLab: "Painel do laboratório",
    dashboardSubtituloLab: "Todas as ordens das clínicas parceiras do Ultra Dental Lab",
    dashboardTituloClinica: "Minhas ordens",
    dashboardSubtituloClinica: "Ordens enviadas pela sua clínica",
    novaOrdemTitulo: "Nova ordem de serviço",
    novaOrdemSubtitulo: "Preencha os dados do caso. O número da ordem é gerado automaticamente.",
    uploadTitulo: "Arraste arquivos aqui ou clique para selecionar",
    uploadSubtitulo: "Envie escaneamentos 3Shape, Medit, Cerec ou iTero e documentos do caso.",
  },
  cores: {
    primaria: "#0D9488",
    primariaEscura: "#0F766E",
    fundo: "#F1F5F4",
    superficie: "#FFFFFF",
    texto: "#0F172A",
    textoSecundario: "#54687A",
    borda: "#DCE6E3",
    sidebarFundo: "#0A1210",
    sidebarTexto: "#DCEAE6",
    sidebarAccent: "#142521",
    sidebarAccentTexto: "#FFFFFF",
    sidebarBorda: "#1F332E",
    sidebarPrimaria: "#2DD4BF",
    statusNeutroBg: "#F1F5F9",
    statusNeutroTexto: "#334155",
    statusInfoBg: "#EFF6FF",
    statusInfoTexto: "#1D4ED8",
    statusAlertaBg: "#FFFBEB",
    statusAlertaTexto: "#92400E",
    statusSucessoBg: "#ECFDF5",
    statusSucessoTexto: "#047857",
    statusErroBg: "#FEF2F2",
    statusErroTexto: "#B91C1C",
  },
  fontes: {
    titulo: "'Space Grotesk', sans-serif",
    corpo: "'IBM Plex Sans', sans-serif",
    mono: "'IBM Plex Mono', monospace",
  },
  logoPath: "/brand/logo.png",
  compatibilidades: ["3Shape", "Medit", "Cerec", "iTero"],
};
