import type { BrandConfig } from "@mvp/ui";

export const brand: BrandConfig = {
  id: "ultra-dental",
  nome: "ULTRA",
  nomeDestaque: "DENTAL LAB",
  tagline: "Fluxo Digital Completo",
  cidade: "Maringá",
  estado: "PR",
  responsavelLabel: "Laboratório",
  responsavelNome: "Ultra Dental Lab",
  headline: "Próteses que devolvem sorrisos.",
  subheadline: "Precisão, previsibilidade e confiança em cada caso.",
  statusFlow: ["Recebido", "Em produção", "Em prova", "Finalizado"],
  statusAprovacao: "Em prova",
  dashboard: {
    statCards: [
      { label: "Casos recebidos", tipo: "status", statuses: ["Recebido"] },
      { label: "Em produção", tipo: "status", statuses: ["Em produção"] },
      { label: "Em prova", tipo: "status", statuses: ["Em prova"] },
      { label: "Finalizados", tipo: "status", statuses: ["Finalizado"] },
      { label: "Casos atrasados", tipo: "atrasadas" },
    ],
  },
  dashboardDestaque: {
    titulo: "Prazo previsível",
    texto: "Você sabe exatamente em que etapa cada peça está.",
  },
  textos: {
    loginTitulo: "Entrar",
    loginSubtitulo: "Acesso da equipe Ultra Dental Lab e das clínicas parceiras.",
    loginBotaoPrincipal: "Entrar",
    loginLinkSecundario: "Acessar como clínica (demonstração)",
    dashboardTituloLab: "Bom dia. Vamos cuidar dos próximos casos.",
    dashboardSubtituloLab: "Controle cada trabalho do scan à finalização.",
    dashboardTituloClinica: "Seu caso, acompanhado em cada etapa.",
    dashboardSubtituloClinica: "Resposta direta com o técnico responsável pelo caso.",
    novaOrdemTitulo: "Novo caso",
    novaOrdemSubtitulo: "Cada peça nasce de um protocolo.",
    uploadTitulo: "Envie os arquivos do caso",
    uploadSubtitulo: "STL, PLY, OBJ, imagens e PDF — do scan à finalização.",
  },
  cores: {
    primaria: "#76C7D8",
    primariaEscura: "#5AA9BB",
    primariaTexto: "#0D1720",
    inputBg: "#0D1720",
    fundo: "#0D1720",
    superficie: "#1B303B",
    texto: "#F4F1EA",
    textoSecundario: "#AAB8BA",
    borda: "#304650",
    sidebarFundo: "#091219",
    sidebarTexto: "#AAB8BA",
    sidebarAccent: "#142632",
    sidebarAccentTexto: "#F4F1EA",
    sidebarBorda: "#304650",
    sidebarPrimaria: "#76C7D8",
    statusNeutroBg: "#1B303B",
    statusNeutroTexto: "#AAB8BA",
    statusInfoBg: "#15242D",
    statusInfoTexto: "#76C7D8",
    statusAlertaBg: "#2A2011",
    statusAlertaTexto: "#D6A85F",
    statusSucessoBg: "#132922",
    statusSucessoTexto: "#6FB28A",
    statusErroBg: "#2A1613",
    statusErroTexto: "#C97970",
  },
  fontes: {
    titulo: "'Manrope', sans-serif",
    corpo: "'Inter', sans-serif",
    mono: "'Sora', sans-serif",
  },
  logoPath: "/brand/logo.png",
  logoFundoClaro: true,
  sidebarLogoSomenteImagem: true,
  compatibilidades: ["3Shape", "Medit", "Cerec", "iTero"],
};
